### PR TITLE
fix StringUtil::indexOfIgnoreCase

### PR DESCRIPTION
**Pull request by ahadas**

### CODE REVIEW

**Comment by terzerm** [comment]
Thanks for raising this.  Fixed slightly differently to keep in sync with the original (String.indexOf).

**Comment by terzerm** [comment]
Fixed in https://github.com/tools4j/unix4j/commit/5bbeedb115c2abce9dd3c96d9d2c0fc43dcaca83

**Comment by ahadas** [comment]
@terzerm hi, when is v0.6 expected to be released?

**Comment by terzerm** [comment]
hi @ahadas yes we are going to release it shortly --- hope this week.

**Pull request closed without merging**
